### ISSUE TITLE
Update footer on egamebook.com

### ISSUE THREAD

**Issue by ruskakimov** [filiph/egamebook#149]
This section of the website is outdated:
![image](https://user-images.githubusercontent.com/5536948/117462576-9e2ed780-af70-11eb-8248-df5b21c04167.png)

Couldn't find a website repo, so I'm posting it here. :)

**Comment by filiph** [comment]
Thank you, [fixed](https://egamebook.com/)!

<img width="1531" alt="Screen Shot 2021-05-28 at 09 28 34" src="https://user-images.githubusercontent.com/919717/120014590-1cdacb80-bf97-11eb-827a-2a6fac6a03b5.png">
