### ISSUE TITLE
Use in other commercial ideas

### ISSUE THREAD

**Issue by DhivakarK-git** [filiph/egamebook#152]
The work and concept of the game are impressive.

> I loved playing **Knights of San Fransisco**... And really liked the experience of it albeit quite short.

It gave me inspiration and methodology to implement an old idea, inspired by something we used to play with as kids. Its just that even with the BSD 3 open-source licence, it doesn't feel right to directly adapt any of the ideas in this repo; especially since the game that implements this idea and mechanism is monetized.

So it'd be great if you could either add it in readme or the website as to what or you would like other indie game devs would adopt this idea or code into their projects.

**Comment by filiph** [comment]
Thanks for being so considerate!

I really mean the license here — please do take this, and do whatever you want with this. If you can make money on it, that's fantastic!

Just note that this repo does not include Knights of San Francisco's UI code (the Flutter app). This is just the "engine", a pure Dart piece of code.

Also, a disclaimer: I can't support folks who take up this codebase in terms of bug fixes or advice. I wanted the code to be public and free, but I can't commit to service work, for obvious reasons (no time). Just thought I'd mention it for posterity.

If you decide to go with this, have fun!
